name: notebook-pytraj
dependencies:
- python=3.4
- pytraj-dev
- numpy
- matplotlib
- pandas
- scikit-learn
- scipy
- mpi4py
- mdview
- chemview
- jupyter
#- ipython-notebook

channels:
  - ambermd
  - anaconda
