name: notebook-pytraj
dependencies:
- python=3.4
- libcpptraj-dev
- lapackamber
- blasamber
- arpack
- pytraj-dev
- numpy
- matplotlib
- pandas
- scikit-learn
- scipy
- mpi4py
- mdview

channels:
  - ambermd
  - anaconda
