name: notebook-pytraj
dependencies:
- python=3.4
- pytraj-dev
- numpy
- matplotlib
- pandas
- scikit-learn
- scipy
- mpi4py
- chemview
- jupyter
- nglview
- parmed
- pysander

channels:
  - ambermd
  - anaconda
  - omnia
